language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - sudo chmod 755 espeak4py/espeak
  - pip install -r build_requirements.txt
  - sed -i 's/\r//' espeak4py/__init__.py

script: python3 test.py

after_success:
  - coverage run test.py
  - coverage xml -o coverage.xml test.py
  - codeclimate-test-reporter