language: python
python:
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

install:
  - sudo chmod 755 espeak4py/espeak
  - ls -l espeak4py
  - ls -l /home/travis/build/sayak-brm/espeak4py/espeak4py
  - pip install codeclimate-test-reporter
#  - pip install .
#  - pip install -r requirements.txt

script: python3 test.py

after_success:
  - coverage run test.py
  - coverage xml -o coverage.xml test.py
  - codeclimate-test-reporter