build: false
version: 0.2.{build}
branches:
  except:
  - gh-pages

environment:
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5.1"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python33"
      PYTHON_VERSION: "3.3.5"
      PYTHON_ARCH: "32"

    - PYTHON: "C:\\Python34"
      PYTHON_VERSION: "3.4.1"
      PYTHON_ARCH: "32"


init:
  - set PATH=%PYTHON%\scripts;%PATH%
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "pip install -r build_requirements.txt"

test_script:
  - "%PYTHON%\\python.exe test.py"

after_test:
  - coverage run test.py
  - coverage xml -o coverage.xml test.py
  - codeclimate-test-reporter