name: Update Personal site project page

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Update site
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        repository: sayakbrm/sayak-brm.github.io
        event-type: update-event
